timezone: Tokyo
encoding: UTF-8

title: "ORTClip"
description: "Send a message instantly, secretly."
url: "https://moutend.github.io/ORTClip/"

markdown: kramdown
permalink: pretty

sass:
  sass_dir:  _scss
  style:    :compressed

exclude:
  - "README.md"
  - "Gemfile"
  - "vendor"
